name = "password-purgatory-logger"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-07-24"

kv_namespaces = [
         { binding = "PASSWORD_PURGATORY", id = "b8fdc719321741e89dbdff5dd26a6712", preview_id = "16eb5cae3508418c875a7f8950e09a68" }
]